CREATE TABLE IF NOT EXISTS posts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    guid VARCHAR(255) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    pubDate DATETIME NOT NULL,
    link VARCHAR(255) NOT NULL,
    categories VARCHAR(255),
    creator VARCHAR(255),
    content TEXT,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
